apiVersion: v1
kind: Secret
metadata:
  name: mongodb-secret
type: Opaque
data:
  mongodb-root-password: ${mongodb_root_password}
  mongodb-replica-set-key: ${mongodb_replica_set_key}
  mongodb-passwords: ${mongodb_passwords}
