apiVersion: v1
kind: Secret
metadata:
  name: online-auction-secret
type: Opaque
data:
  MONGODB_URI: ${MONGODB_URI}
  SMTP_APP_PASSWORD: ${SMTP_APP_PASSWORD}
  JWT_KEY: ${JWT_KEY}
  CLOUDINARY_NAME: ${CLOUDINARY_NAME}
  CLOUDINARY_KEY: ${CLOUDINARY_KEY}
  CLOUDINARY_SECRET: ${CLOUDINARY_SECRET}
  REDIS_URL: ${REDIS_URL}
