apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: standard-csi
provisioner: pd.csi.storage.gke.io
volumeBindingMode: WaitForFirstConsumer
allowVolumeExpansion: true
---

apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: test-pvc
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
  storageClassName: standard-csi
---

apiVersion: v1
kind: Pod
metadata:
  name: test-pd-pod
spec:
  containers:
  - name: writer
    image: busybox
    command: [ "sh", "-c", "echo Hello GCP PD > /mnt/test/data && sleep 3600" ]
    volumeMounts:
    - mountPath: /mnt/test
      name: pd-volume
  volumes:
  - name: pd-volume
    persistentVolumeClaim:
      claimName: test-pvc
